import { Newsreader, Flow_Block, Rajdhani } from 'next/font/google';
import Footer from '@/containers/Footer';
import './globals.css';
import Header from '@/containers/Header';

const rajDhani = Rajdhani({
  weight: ['400', '500', '600', '700'],
  style: ['normal'],
  subsets: ['latin'],
  variable: '--font-rajdhani',
});

const flowBlock = Flow_Block({
  weight: '400',
  style: ['normal'],
  subsets: ['latin'],
  variable: '--font-block',
  preload: true,
});

export const metadata = {
  title: 'OpenStack Hub',
  description: 'Generated by create next app',
  charset: 'UTF-8',
};

// export async function generateMetadata({ params }) {
//   const metaData = await getSEOData("home");

//   const seo = metaData?.data?.banner.data?.attributes?.seo;

//   const facebook = seo.metaSocial?.find((x) => x?.socialNetwork === "Facebook");
//   const twitter = seo.metaSocial?.find((x) => x?.socialNetwork === "Twitter");

//   let twitterMeta = {};
//   if (twitter) {
//     twitterMeta = {
//       twitter: {
//         card: "summary_large_image",
//         title: twitter.title,
//         description: twitter.description,
//         siteId: "1467726470533754880",
//         creator: "@nextjs",
//         creatorId: "1467726470533754880",
//         images: [twitter.image?.data?.attributes?.url || ""],
//       },
//     };
//   }

//   let facebookMeta = {};
//   if (facebook) {
//     facebookMeta = {
//       openGraph: {
//         title: facebook.title,
//         description: facebook.description,
//         url: `https://thespecialcharacter.com`,
//         siteName: "Openstack Hub",
//         images: [
//           {
//             url: facebook.image?.data?.attributes?.url || "",
//             width: 800,
//             height: 600,
//           },
//         ],
//         locale: "en-US",
//         type: "website",
//       },
//     };
//   }

//   const defaultSEO = {
//     description: seo.metaDescription,
//     title: {
//       template: "%s | Openstack Hub",
//       default: `${seo.metaTitle} | Openstack Hub`,
//     },
//     keywords: seo.keywords,
//   };

//   return {
//     applicationName: "Openstack Hub",
//     themeColor: "#fff",
//     generator: "Next.js",
//     referrer: "origin-when-cross-origin",
//     authors: [{ name: "Yagnesh Modh" }],
//     colorScheme: "light",
//     creator: "Yagnesh Modh",
//     publisher: "Openstack Hub",
//     viewport: {
//       width: "device-width",
//       initialScale: 1,
//       maximumScale: 1,
//     },
//     formatDetection: {
//       email: false,
//       address: false,
//       telephone: false,
//     },
//     appleWebApp: {
//       title: "Openstack Hub",
//       statusBarStyle: "black-translucent",
//     },
//     icons: {
//       icon: [
//         { url: "/icons/tsc.svg", type: "image/svg+xml" },
//         {
//           url: "/favicon/favicon-16x16.png",
//           sizes: "16x16",
//           type: "image/png",
//         },
//         {
//           url: "/favicon/favicon-32x32.png",
//           sizes: "32x32",
//           type: "image/png",
//         },
//       ],
//       shortcut: ["/shortcut-icon.png"],
//       apple: [
//         // { url: '/apple-icon.png' },
//         {
//           url: "/favicon/apple-touch-icon.png",
//           sizes: "180x180",
//           type: "image/png",
//         },
//       ],
//       other: [
//         // {
//         //   rel: 'apple-touch-icon-precomposed',
//         //   url: '/apple-touch-icon-precomposed.png',
//         // },
//         {
//           rel: "mask-icon",
//           url: "/favicon/safari-pinned-tab.svg",
//           // color: '#ffc40d',
//         },
//       ],
//     },
//     manifest: "/favicon/site.webmanifest",
//     ...defaultSEO,
//     ...twitterMeta,
//     ...facebookMeta,
//   };
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" sizes="any" />
      </head>
      <body
        className={`${rajDhani.variable} font-sans   ${flowBlock.variable} font-cursive `}
      >
        <Header />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
